print("Hello World")
print("This is a Python script named pythoncoba.py")
print("It demonstrates a simple print statement.")
print("You can run this script using a Python interpreter.")
print("Enjoy coding in Python!")
print("Goodbye from pythoncoba.py")
print("This is the end of the script.")
print("Thank you for using pythoncoba.py")
print("Have a great day!")
print("See you next time!")
print("This is a simple demonstration of Python scripting.")
print("Python is a versatile programming language.")
print("You can create complex applications with Python.")
print("Keep learning and exploring Python!")
print("Python has a large standard library.")
print("You can find many resources online to learn Python.")
print("Happy coding!")
print("This script is just a starting point.") 
print("Feel free to modify and expand it.")
print("Experiment with different Python features.") 
print("The possibilities with Python are endless.")